spring.application.name=crud
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/habitdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
app.jwt.secret=ZGV2LXNlY3JldC1uaWNodC1pbi1wcm9kLWJpdHRlLW1pbi0zMi1ieXRlcw==
app.jwt.expiration-ms=86400000
reminder.service.url=${REMINDER_SERVICE_URL:http://localhost:3001}
