version: '3.8'
services:
  java-db:
    image: postgres
    container_name: java-db
    environment:
      POSTGRES_PASSWORD: java
      POSTGRES_DB: habit_tracker_java_service
    ports:
      - "5432:5432"
    volumes:
      - java_postgres_data:/var/lib/postgresql/data

  node-db:
    image: postgres
    container_name: node-db
    environment:
      POSTGRES_PASSWORD: nodejs
      POSTGRES_DB: habit_tracker_node_service
    ports:
      - "5433:5432" # Different host port to avoid conflict
    volumes:
      - node_postgres_data:/var/lib/postgresql/data
volumes:
  java_postgres_data:
  node_postgres_data:
